Rules:
  - id: "string-for-url"
    delimiter: ";"
    type: http
    http:
      url: "http://localhost:3000/api/test"
      method: POST
      headers:
        - name: "content-type"
          value: ""
        - name: "mykey"
          value: "myvalue"
      auth:
        type: bearer
        value: CHANGEME
      payload_key: "data"
    each_line:
      - map:
          - name: "Last name"
            to: "lastName"
            required: true
          - name: "First name"
            to: "firstName"
          - name: "id"
            fill:
              type: "string"
              prefix: "changeme-"
              value: "row_number"
          - name: "groups"
            fill:
              type: "array"
              value:
                - "user"
                - "company default group"
          - name: "Location"
            insert_into: "groups"
          - name: "Password"
            handlers:
              - "hasher"
        validation:
          - field: "Last name"
            type: "string"
          - field: "First name"
            type: "string"
Handlers:
  - name: "hasher"
    persistent: true
